# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from python.grpc import sensor_data_pb2 as python_dot_grpc_dot_sensor__data__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in python/grpc/sensor_data_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DataStreamerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamData = channel.unary_stream(
                '/datastream.DataStreamer/StreamData',
                request_serializer=python_dot_grpc_dot_sensor__data__pb2.Empty.SerializeToString,
                response_deserializer=python_dot_grpc_dot_sensor__data__pb2.DataPoint.FromString,
                _registered_method=True)


class DataStreamerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StreamData(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DataStreamerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamData,
                    request_deserializer=python_dot_grpc_dot_sensor__data__pb2.Empty.FromString,
                    response_serializer=python_dot_grpc_dot_sensor__data__pb2.DataPoint.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'datastream.DataStreamer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('datastream.DataStreamer', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DataStreamer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StreamData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/datastream.DataStreamer/StreamData',
            python_dot_grpc_dot_sensor__data__pb2.Empty.SerializeToString,
            python_dot_grpc_dot_sensor__data__pb2.DataPoint.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
